### ISSUE TITLE
Nerd font not working

### ISSUE THREAD

**Issue by dlvhdr** [ldelossa/gh.nvim#10]
I'm using FiraCode with Alacritty (terminal emulator) in tmux and the icons don't display properly.
![image](https://user-images.githubusercontent.com/6196971/167309722-91447e41-38f8-4f17-9b9d-ed0e0ea8cdb1.png)

**Comment by ldelossa** [comment]
Its possible the config is not working properly. Did you update config "icon_set" value?

**Comment by ldelossa** [comment]
Hey there, so I just checked on my end. The nerd fonts seem to be working OK:

```
require('litee.gh').setup({
    icon_set = "nerd",
})
```

Is this your config? Also, do you render the icons here correctly?

https://github.com/ldelossa/litee.nvim/blob/main/lua/litee/lib/icons/init.lua

**Comment by dlvhdr** [comment]
I tried checking on my repo gh-dash but the plugin was stuck again

**Comment by ldelossa** [comment]
@dlvhdr please try again with latest commit and follow #8 - this fixes I think your issue with opening the PR.

**Comment by cloudlena** [comment]
I'm using the exact same setup (FiraCode with Alacritty) and for me, it's working fine with the following config:

```lua
    use({
        "ldelossa/gh.nvim",
        requires = { "ldelossa/litee.nvim" },
        config = function()
            require("litee.lib").setup()
            require("litee.gh").setup({
                icon_set = "nerd",
            })
        end,
    })
```

This works well, but I'm getting `nil` instead of some icons:

![screenshot-2022-05-16-21-51-28](https://user-images.githubusercontent.com/6780471/168671261-9da92263-e961-4c93-ad1d-e93d30902b08.png)

Furthermore, the `#` icon seems to be misconfigured. Wouldn't it make more sense to just use the `#` character instead?

**Comment by ldelossa** [comment]
Cool that looks right. I'll fix those nils.

**Comment by ldelossa** [comment]
@cloudlena - Please pull latest "litee.nvim" commit. this will fix those nils.

**Comment by cloudlena** [comment]
Thanks, @ldelossa. The `nil`s are indeed fixed :+1:
